apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
  namespace: <+infra.namespace>
  labels:
    app: hello-cronjob
    managed-by: harness
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            command: ['sh', '-c']
            args:
            - |
              echo "Hello from Kubernetes CronJob!"
              echo "Current time: $(date)"
              echo "Deployed via Harness Pipeline"
              sleep 5
              echo "Task completed successfully!"
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid